# Generated by Django 5.0 on 2024-01-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('address', models.TextField()),
                ('zip', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('payment_method', models.CharField(choices=[('cashOnDelivery', 'Cash on Delivery'), ('cardPayment', 'Card Payment')], max_length=20)),
                ('cardnumber', models.IntegerField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, max_length=16, null=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
