# Generated by Django 5.0 on 2024-01-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='author_name',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
